---

- name: Install list of packages
  action: apt pkg={{item}} state=installed
  with_items:
  - apache2
  - mysql-server

- name: Start services
  action: service name={{item}} state=started
  with_items:
  - apache2
  - mysql
